[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hercsis"
version = "0.0.1"
dependencies = [
    "sqlalchemy >= 2.0.41"
]
authors = [
    { name="Ben Taft", email="ben.taft@career2cradle.org"},
]
description = "A student information system in SQLAlchemy"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: SQL",
    "Topic :: Database",
    "Operating System :: OS Independent",
    "Intended Audience :: Education",
    "License :: OSI Approved :: MIT License",
]
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://github.com/higherX4Racine/hercsis"

[tool.pytest.ini_options]
addopts = "--cov=hercsis"
testpaths = [
    "tests",
]